"""empty message

Revision ID: 832f8956238e
Revises: 879680cc96ba
Create Date: 2021-06-02 21:44:49.777283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832f8956238e'
down_revision = '879680cc96ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_recipient_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    # ### end Alembic commands ###
