"""empty message

Revision ID: 879680cc96ba
Revises: cea08f02f7a0
Create Date: 2021-06-02 19:21:21.903089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879680cc96ba'
down_revision = 'cea08f02f7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
