"""empty message

Revision ID: a05fbcb4bd54
Revises: ffd66406ef45
Create Date: 2021-06-02 16:36:48.987196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05fbcb4bd54'
down_revision = 'ffd66406ef45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messsages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_a', sa.Integer(), nullable=True),
    sa.Column('match_b', sa.Integer(), nullable=True),
    sa.Column('isSeen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('messsages')
    # ### end Alembic commands ###
