"""empty message

Revision ID: 10b9786b4906
Revises: 832f8956238e
Create Date: 2021-06-11 12:02:58.446100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9786b4906'
down_revision = '832f8956238e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('left_swipes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('left_swipes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_swipes_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'left_swipes_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('left_swipes')
    # ### end Alembic commands ###
