"""empty message

Revision ID: ffd66406ef45
Revises: ffdc0a98111c
Create Date: 2021-06-02 16:15:42.824823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd66406ef45'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('f_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('l_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Numeric(precision=15), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'l_name')
    op.drop_column('users', 'f_name')
    # ### end Alembic commands ###
