"""empty message

Revision ID: 8196bc5e42f4
Revises: 10b9786b4906
Create Date: 2021-07-16 10:55:46.415548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8196bc5e42f4'
down_revision = '10b9786b4906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
